### ISSUE TITLE
Include clear instructions on how to create Polls in Zoom

### ISSUE THREAD

**Issue by pedrohbraga** [QCBSRworkshops/presenter-developer-protocol#7]
While there is a link referring to instructions on how to work with Zoom, we need to provide clear instructions on how to create polls in Zoom. Instructors need to know that they must prepare the polls before the workshops.

Apparently, there is also a way to import polls to Zoom from CSV documents. If this is possible, then these files can be produced in advance, in their corresponding languages, and uploaded to each workshop repository.

If considered, guidelines should be added to both presenter and developer guidelines.

Suggested resource: 
https://wiki.edtech.hofstra.edu/display/KB/Creating+Zoom+Polls

Important: If this issue is addressed, only close it if changes are made to both languages.

**Comment by katherinehebert** [comment]
There are now instructions about poll creation in both EN and FR, with a link to a helpful resource. 🎉
